### PR TITLE
Fix output fields order inconsistent with the input (#81)

### LINKED ISSUE #81: Output field order inconsistent with the input
```shell
$ jackson-jq -n '{a:{depth:1,b:{depth:2}}}'
{
  "a" : {
    "b" : {
      "depth" : 2
    },
    "depth" : 1
  }
}

$ jq -n '{a:{depth:1,b:{depth:2}}}'
{
  "a": {
    "depth": 1,
    "b": {
      "depth": 2
    }
  }
}
```

Problem may be here: 
```java
// method: net.thisptr.jackson.jq.internal.tree.ObjectConstruction#apply
public void apply(final Scope scope, final JsonNode in, final Path ipath, final PathOutput output, final boolean requirePath) throws JsonQueryException {
  final Map<String, JsonNode> tmp = new HashMap<>();
  applyRecursive(scope, in, output, fields, tmp);
}
```
Should use LinkedHashMap instead, and testcase seem doesn't care field order.
[net/thisptr/jackson/jq/internal/misc/JsonNodeComparator.java#L94-L94](https://github.com/eiiches/jackson-jq/blob/develop/1.x/jackson-jq/src/main/java/net/thisptr/jackson/jq/internal/misc/JsonNodeComparator.java#L94-L94)

### PR DESCRIPTION
**Pull request by Shawyeok**
Fix #81

### CODE REVIEW

File: jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java [hunk 1]
```diff
@@ -196,6 +197,20 @@ private void test(final TestCase tc, final Version version) throws Throwable {
 			assertThat(failed).describedAs("unexpectedly succeeded").isTrue();
 	}
 
+	private void assertEquals(List<JsonNode> expected, List<JsonNode> actual, String description, Object... args) {
+		assertThat(actual).as(description, args)
+				.usingComparator((o1, o2) -> {
+					try {
+						String o1Json = JSON_MAPPER.writeValueAsString(o1);
+						String o2Json = JSON_MAPPER.writeValueAsString(o2);
+						return o1Json.compareTo(o2Json);
```
Comment (eiiches) [inline jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java]: It'd be better if you can compare the two values without converting them to strings first. We probably have to implement a new equality function that i) ignores the number type differences (`IntNode`, `LongNode`, `DoubleNode`, ...so that we don't have to distinguish between `3` and `3.0` in test cases) and ii) is sensitive to the order of the keys.

File: jackson-jq/src/main/java/net/thisptr/jackson/jq/internal/tree/ObjectConstruction.java [hunk 2]
```diff
@@ -26,7 +26,7 @@ public void add(final FieldConstruction field) {
 
 	@Override
 	public void apply(final Scope scope, final JsonNode in, final Path ipath, final PathOutput output, final boolean requirePath) throws JsonQueryException {
-		final Map<String, JsonNode> tmp = new HashMap<>();
+		final Map<String, JsonNode> tmp = new LinkedHashMap<>(fields.size());
```
Comment (eiiches) [inline jackson-jq/src/main/java/net/thisptr/jackson/jq/internal/tree/ObjectConstruction.java:29]: nice optimization btw :+1:

**Review by eiiches — CHANGES_REQUESTED** [review]
Thanks for taking time for the issue and submitting the patch!

File: jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java (hunk 1 above)
Comment (Shawyeok) [reply jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java]: Done, keep using `JsonNodeComparator`

**Comment by Shawyeok** [comment]
@eiiches Request for review.

File: jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java (hunk 1 above)
Comment (eiiches) [reply jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java]: Sorry for the delay.

Unfortunately, we can't change how `JsonNodeComparator` compares two objects. The primary use of the comparator is `sort_by` and the comparison is explicitly specified as:
> first they're compared by comparing their sets of keys (as arrays in sorted order), and if their keys are equal then the values are compared key by key. -- https://stedolan.github.io/jq/manual/v1.6/#sort,sort_by(path_expression)

So we need to leave the comparator as it was and implement a new independent equality function solely for the tests. Let me handle the test part and I'll shortly merge this PR with my commit added.

Comment (eiiches) [reply jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java]: Can you undo the changes to `jackson-jq/src/main/java/net/thisptr/jackson/jq/internal/misc/JsonNodeComparator.java` and `jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java`, squash and force-push to the branch? I can edit the commit myself, but if I do that, this PR won't be marked as Merged after merge.

Comment (Shawyeok) [reply jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java]: Done.

Comment (eiiches) [reply jackson-jq/src/test/java/net/thisptr/jackson/jq/JsonQueryTest.java]: Thanks!

**Review by eiiches — APPROVED** [review]
