### PR TITLE
[Fix #381] Fixing null pointer

### LINKED ISSUE #381: NullPointerException when property is not present in context json
I think the best way to ilustrate the issue is through a JQplay snapshpt
image

When trying to evalute that using the library, the code throws a null pointer exception
```
java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.isIntegralNumber()" because "lhs" is null
	at net.thisptr.jackson.jq.internal.operators.PlusOperator.apply(PlusOperator.java:19)
	at net.thisptr.jackson.jq.internal.tree.binaryop.assignment.ComplexAssignment.lambda$null$1(ComplexAssignment.java:41)
	at net.thisptr.jackson.jq.path.ObjectFieldPath.mutate(ObjectFieldPath.java:69)
	at net.thisptr.jackson.jq.path.ObjectFieldPath.lambda$mutate$1(ObjectFieldPath.java:52)
	at net.thisptr.jackson.jq.path.RootPath.mutate(RootPath.java:30)
	at net.thisptr.jackson.jq.path.ObjectFieldPath.mutate(ObjectFieldPath.java:51)
	at net.thisptr.jackson.jq.path.Path.mutate(Path.java:20)
	at net.thisptr.jackson.jq.internal.tree.binaryop.assignment.ComplexAssignment.lambda$apply$2(ComplexAssignment.java:41)
	at net.thisptr.jackson.jq.Output.emit(Output.java:14)
	at net.thisptr.jackson.jq.internal.tree.ArrayConstruction.apply(ArrayConstruction.java:28)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at net.thisptr.jackson.jq.internal.tree.binaryop.assignment.ComplexAssignment.apply(ComplexAssignment.java:29)
	at net.thisptr.jackson.jq.Expression.apply(Expression.java:11)
	at io.serverlessworkflow.impl.expressions.JQExpression.eval(JQExpression.java:184)
	at io.serverlessworkflow.impl.executors.AbstractTaskExecutor.lambda$2(AbstractTaskExecutor.java:94)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.serverlessworkflow.impl.executors.AbstractTaskExecutor.apply(AbstractTaskExecutor.java:93)
	at io.serverlessworkflow.impl.WorkflowUtils.processTaskList(WorkflowUtils.java:155)
	at io.serverlessworkflow.impl.executors.ForExecutor.internalExecute(ForExecutor.java:55)
	at io.serverlessworkflow.impl.executors.AbstractTaskExecutor.apply(AbstractTaskExecutor.java:92)
	at io.serverlessworkflow.impl.WorkflowUtils.processTaskList(WorkflowUtils.java:155)
	at io.serverlessworkflow.impl.WorkflowInstance.<init>(WorkflowInstance.java:36)
	at io.serverlessworkflow.impl.WorkflowDefinition.execute(WorkflowDefinition.java:100)
	at io.serverlessworkflow.impl.WorkflowDefinitionTest.testWorkflowExecution(WorkflowDefinitionTest.java:44)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)


```

### PR DESCRIPTION
**Pull request by fjtirado**
Fix https://github.com/eiiches/jackson-jq/issues/381

### CODE REVIEW

**Comment by eiiches** [comment]
Thank you for reporting and submitting a patch!

This clearly fixes the issue for `+=` case, but I'm not sure if this patch is enough to fix the NPE for other operators (such as `|=`) and other path-related functions (`setpath`, `delpaths`, etc.). So, I'm wondering if we should fix ObjectFieldPath#mutate() instead. Let me take a look again tomorrow.

**Comment by fjtirado** [comment]
@eiiches Yes, I was tempted to change mutate method, but prefer to be conservative and just fix it for all complex mutations.

**Comment by fjtirado** [comment]
> Thank you for reporting and submitting a patch!
> 
> This clearly fixes the issue for `+=` case, but I'm not sure if this patch is enough to fix the NPE for other operators (such as `|=`) and other path-related functions (`setpath`, `delpaths`, etc.). So, I'm wondering if we should fix ObjectFieldPath#mutate() instead. Let me take a look again tomorrow.

I filed a new commit that change the mutate. To be honest, I was lazy and did not want to search which mutate implementation I have to change. Now that you give me the clue, I have no excuse ;)

File: jackson-jq/src/main/java/net/thisptr/jackson/jq/path/ObjectFieldPath.java [hunk 1]
```diff
@@ -66,8 +66,9 @@ private static JsonNode mutate(JsonNode in, final String key, final Mutation mut
 				final Entry<String, JsonNode> entry = iter.next();
 				newobj.set(entry.getKey(), entry.getValue());
 			}
-			final JsonNode newval = mutation.apply(newobj.get(key));
-			if (newval != null)
+			JsonNode newval = newobj.get(key);
+			newval = mutation.apply(newval != null ? newval : NullNode.getInstance());
+			if (newval != null && !newval.isNull())
```
Comment (eiiches) [inline jackson-jq/src/main/java/net/thisptr/jackson/jq/path/ObjectFieldPath.java]: JSON `null` (NullNode) is a valid value for object fields, so `&& !newval.isNull()` is unnecessary.
```
$ jq -c '.foo += null' <<< '{}'
{"foo":null}
```
Other than that, the patch looks good :+1:

Comment (fjtirado) [reply jackson-jq/src/main/java/net/thisptr/jackson/jq/path/ObjectFieldPath.java]: If I remove the isNull, a lot of test will fail (acutally it took me a while to figure out that).  The reason is the same why you add the original null check, to prevent null values to be added to the object (you have some unit test to prevent that)

**Comment by eiiches** [comment]
After taking a closer look at the code, I'm convinced that your first patch was the right way to fix the issue. Can you push the original patch again? Sorry for the confusion and taking me so long to respond.

A couple of remarks:

* In the current implementation, null, when used as an argument to Path.Mutation#apply(), represents a missing field in an object or an out-of-range index in an array. ArrayIndexPath#mutate() explicitly passes null to Path.Mutation.
  * While I'm not sure if the distinction between a missing field and JSON null is a requirement, it does seem better to maintain this distinction.
* Other callers of Path#mutate() already handle nulls when necessary (e.g. UpdateAssignment). The only place that lacks null handling is ComplexAssignment, which the original patch addressed.

**Comment by fjtirado** [comment]
@eiiches Original approach restored. Thanks a lot for your inshights and time
